name: KeeTrayTOTP PR Build Mono

on: [pull_request]

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install xvfb-run
      run: sudo apt -y install xvfb

    - name: Download nuget.exe
      run: wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe 

    - name: nuget restore
      run: mono nuget.exe restore

    - name: MSBuild
      run: msbuild /target:build

    - name: Run tests
      run: xvfb-run dotnet vstest KeeTrayTOTP.Tests/bin/Debug/KeeTrayTOTP.Tests.dll